### PR TITLE
163 fall back on tiger

### PR DESCRIPTION
**Pull request by CanyonFoot**
Makes the basic change described in the issue: New wrapper that tries for the CB file, and, on exception, uses the tiger function. I made a couple other changes to improve support for older geometry files with some additional string processing.

### CODE REVIEW

**Comment by CanyonFoot** [comment]
Looking into the PUMA issue.. I think I know the cause

**Comment by vengroff** [comment]
> Looking into the PUMA issue.. I think I know the cause

Try running

```shell
poetry run python censusdis/symbolic.py datasets.py
```

and commiting the resulting change. We need to better document the need to do this to keep the 
file up to date. Or we need to perhaps not run this test on all branches and make it more of a manual
thing we do every once in a while. There are new data sets far to often.

**Comment by vengroff** [comment]
Do you want to add a test to `test_maps.py` like some of the existing tests that plot maps and compare them to a reference `.png` file? The idea would be to do this for a case that triggers the tiger map case and make sure it works.

**Comment by CanyonFoot** [comment]
Yes I can add that test.

**Comment by vengroff** [comment]
I looked at it a little more closely and I think the image match testing could use just a bit of refactor. I don't know that that is closely related enough to this PR to bother with it. So I think it's safe to not add that test now. I'll add another issue to deal with that.

**Review by vengroff — COMMENTED** [review]
I'll grab these two.

**Review by vengroff — APPROVED** [review]

**Pull request merged**
