### PR TITLE
Fix Pandas deprecation warnings in tests

### PR DESCRIPTION
**Pull request by arilamstein**
Part of #282 (Clear up pandas deprecation warnings). 

This fixes one of the warnings that occurs during a run of pytest:

```
tests/test_geo_integration.py::AddInferredGeographyTestCase::test_multi_year_no_maps
  /Users/arilamstein/censusdis/censusdis/data.py:1710: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
    .apply(
```

Locally the test suite for test_geo_integration has no additional failures or warnings.  However, a full run of pytest locally has one test fail (`test_integration.py::SymbolicInsertTestCase::test_insert_name_link`). But that seems unrelated to my change so I thought to make this PR and see if CI tests have the same issue.

### CODE REVIEW

**Comment by arilamstein** [comment]
Thanks for rerunning the test workflow. That is the same failure I saw locally which I thought was likely unrelated to my change.

In retrospect, I should have done this yesterday. But when I trigger that test on `main` with `poetry run pytest tests/test_integration.py -k SymbolicInsertTestCase` I get the same error. 

At first glance I am not sure what that test is doing (I am new to the codebase), but since I can reproduce it in `main` I think it's probably unrelated to my change. Is it a known issue?

I will look into it now.

**Comment by arilamstein** [comment]
@vengroff  can you please tell me how this PR looks to you?

When I look at the test runs I see no Pandas deprecation warnings, so I think it might allow you to close #282. (See, for example, the results of the latest test run: https://github.com/censusdis/censusdis/actions/runs/12364277068/job/34562812300?pr=313).

In the test matrix 3.12 on windows-latest does have errors. But these seem to all be related to the LODES tests being unable to connect to the Census API, and I'm pretty sure that those errors are unrelated to my checkin.

**Comment by vengroff** [comment]
The windows tests have been a bit flaky, and I agree it has nothing to do with this PR.

**Review by vengroff — APPROVED** [review]
Thanks for this. Just waiting for test jobs to run.

**Pull request merged**
