### PR TITLE
Added Slow Water Removal Demo

### PR DESCRIPTION
**Pull request by audreymarthin**
Utilized time magic to track how long it takes to remove water

### CODE REVIEW

**Review by vengroff — CHANGES_REQUESTED** [review]
Looks good. Just a few small comments.

1. I think maybe you can drop down to the block group level instead of the census tract level to emphasize the slowness by using a larger data set.
2. With a larger data set you may be able to use %time instead of %timeit.
3. Formattingwise, the calls to `ced.download` are a little on the wide side. For a demo notebook I usually like to put one argument per line so it's easy to see all the arguments at once. 
4. Maybe add Harford County and even a couple more counties going down the eastern shore to really emphasize the water effects on the map on both sides of the bay. You can make a constant `COUNTIES=[...]` at the top so you don't have to hard-code the list in both places.

Overall, looks like a great first PR.

**Comment by audreymarthin** [comment]
Thank you for the comments, Darren. I will work on these changes and update them.

**Comment by vengroff** [comment]
You are welcome. Also, quick reminder, please run 

```shell
black .
```

and 

```shell
flake8 .
``` 

before you commit. These are supposed to be part of the github actions but I have it slightly misconfigured so it is not properly triggered on pull requests from clones. I'll fix that separatly.

**Comment by audreymarthin** [comment]
Thank you for reminding me! I will definitely do that for the next commit.

**Comment by audreymarthin** [comment]
Hi Darren, I have just updated the changes per your feedback and I have also run black and flake8 before the commit.

**Review by vengroff — APPROVED** [review]
I see you switched from MD to RI.

**Pull request merged**
